import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/common/nav";
import { geistSans, pretendard } from "@/config/font";
import Footer from "@/components/common/footer";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body className={`${geistSans.variable} antialiased`}>
        <main className="w-dvw min-h-dvh relative flex flex-col">
          <Nav />
          <div className="flex-grow flex flex-col">{children}</div>
          <Footer />
        </main>
        <Toaster position="bottom-center" richColors />
      </body>
    </html>
  );
}
